import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

//👇 Import Open Sans font
import { Inconsolata } from "next/font/google"
//👇 Configure our font object
const inconsolata = Inconsolata({ subsets: ["latin"] })
//👇 Import Open Sans font
import { Secular_One } from "next/font/google"
//👇 Configure our font object
const secularOne = Secular_One({ subsets: ["latin"], weight: "400" })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inconsolata.className} ${secularOne.className}`}>{children}</body>
    </html>
  )
}
